server:
  port: 9100

spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true
    user:
      name: hsc
      password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:8100/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
    #register-with-eureka: false
    #fetch-registry: false