server:
  port: 7788 #服务端口
spring:
  application:
    name: microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/HSCSSHK/MySpringCloud.git
          search-paths:
          - springcloudconfig		#配置文件目录地址
          #username: HSCxxxx	    #github账号（公有项目不需要设置）
          #password: Gitxxxxxxxxxxxxxxx 	#github密码（公有项目不需要设置）
      label: master	#分支名称
eureka:
  client:
    service-url:
           defaultZone: http://hsc:123456@127.0.0.1:8100/eureka/,http://hsc:123456@127.0.0.1:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}###${server.port}
